// Code generated by protoc-gen-mgorm. DO NOT EDIT.
package common

import (
	"context"

	"fmt"
	"time"
	"math/rand"

	"github.com/995933447/mgorm"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"github.com/995933447/mgorm/mgorm-example/base"
)

type Desc2Orm struct {
	Lang string `json:"language" bson:"language"`
}

const (
	Desc3DbName   = "example_db_%d"
	Desc3TbName   = "desc3"
	Desc3ConnName = "default_%d"

	Desc3TtlSec = 0 * 24 * 3600
)

// 索引
var desc3IndexKeys = []string{}

var desc3UniqueIndexKeys = []string{}

var desc3ExpireIndexKeys = []string{
	"expire_at",
}

type Desc3Orm struct {
	ID        primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	Lang      string             `json:"lang,omitempty" bson:"lang,omitempty"`
	Corp      *base.Corp         `json:"corp,omitempty" bson:"corp,omitempty"`
	App       *base.AppOrm       `json:"app,omitempty" bson:"app,omitempty"`
	CreatedAt time.Time          `json:"created_at,omitempty" bson:"created_at,omitempty"`
	UpdatedAt time.Time          `json:"updated_at,omitempty" bson:"updated_at,omitempty"`
	ExpireAt  time.Time          `json:"expire_at,omitempty" bson:"expire_at,omitempty"`
}

var desc3OrmCache mgorm.Cache

func SetDesc3OrmCache(cache mgorm.Cache) {
	desc3OrmCache = cache
}

var onDesc3OrmQueryDone mgorm.OnQueryDoneFunc

func SetDesc3OrmOnQueryDone(fn mgorm.OnQueryDoneFunc) {
	onDesc3OrmQueryDone = fn
}

func NewDesc3Model(connIdx int64, dbIdx int64) *Desc3Model {
	cache := desc3OrmCache
	if cache == nil {
		cache = mgorm.DefaultCache
	}
	orm := mgorm.NewOrm(
		fmt.Sprintf(Desc3ConnName, connIdx),
		fmt.Sprintf(Desc3DbName, dbIdx),
		Desc3TbName,
		false,
		cache,
		desc3IndexKeys,
		desc3UniqueIndexKeys,
		desc3ExpireIndexKeys,
	)
	onQueryDoneFunc := onDesc3OrmQueryDone
	if onQueryDoneFunc == nil {
		onQueryDoneFunc = mgorm.OnQueryDone
	}
	orm.SetOnQueryDone(onQueryDoneFunc)
	return &Desc3Model{
		Model: mgorm.Model[Desc3Orm]{
			Orm:    orm,
			Cached: false,
		},
	}
}

type Desc3Model struct {
	mgorm.Model[Desc3Orm]
}

func (m *Desc3Model) NormalizeOrmForInsert(data *Desc3Orm) {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = data.CreatedAt
	if data.ExpireAt.IsZero() {
		r := rand.New(rand.NewSource(time.Now().UnixNano()))
		data.ExpireAt = time.Now().Add((Desc3TtlSec + time.Duration(r.Int63n(10800))) * time.Second)
	}
}

func (m *Desc3Model) InsertOneIgnoreConflict(ctx context.Context, data *Desc3Orm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOneIgnoreConflict(ctx, data)
	return err
}

func (m *Desc3Model) InsertOne(ctx context.Context, data *Desc3Orm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOne(ctx, data)
	return err
}

func (m *Desc3Model) InsertMany(ctx context.Context, dataList []*Desc3Orm) error {
	var ins []any
	for _, data := range dataList {
		m.NormalizeOrmForInsert(data)
		ins = append(ins, data)
	}
	_, err := m.Model.InsertMany(ctx, ins)
	return err
}

func (m *Desc3Model) Update(ctx context.Context, data *Desc3Orm) (*mongo.UpdateResult, error) {
	dataB, err := mgorm.ToBsonM(data)
	if err != nil {
		return nil, err
	}
	dataB["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": dataB["_id"]}, bson.M{"$set": dataB})
}

func (m *Desc3Model) UpdateOne(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": data})
}

func (m *Desc3Model) UpdateMany(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateMany(ctx, filter, bson.M{"$set": data})
}

func (m *Desc3Model) Upsert(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$setOnInsert": insertData})
}

func (m *Desc3Model) UpInc(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$inc": data, "$set": bson.M{"updated_at": time.Now()}, "$setOnInsert": insertData})
}

func (m *Desc3Model) UpAndInc(ctx context.Context, filter any, data, incdata bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$inc": incdata, "$setOnInsert": insertData})
}

func (m *Desc3Model) DeleteOne(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteOne(ctx, filter)
}

func (m *Desc3Model) DeleteMany(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteMany(ctx, filter)
}

func (m *Desc3Model) UpdateOneByID(ctx context.Context, id string, data bson.M) (*mongo.UpdateResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": objId}, bson.M{"$set": data})
}

func (m *Desc3Model) DeleteOneByID(ctx context.Context, id string) (*mongo.DeleteResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	return m.Model.DeleteOne(ctx, bson.M{"_id": objId})
}

func (m *Desc3Model) FindOneByID(ctx context.Context, id string) (*Desc3Orm, error) {
	var data Desc3Orm
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	filter := bson.M{"_id": objId}
	cacheKey := fmt.Sprintf("_id:%s", id)
	err = m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}
