// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: user.proto

package user

import (
	common "github.com/995933447/mgorm/mgorm-example/common"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type User struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username  string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age       int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Balance   float32                `protobuf:"fixed32,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Active    bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Score     float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	Avatar    []byte                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Tags      map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Interests []string               `protobuf:"bytes,10,rep,name=interests,proto3" json:"interests,omitempty"`
	// 嵌套对象
	Address *Address `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	// 嵌套 repeated 对象
	HistoryAddresses []*Address               `protobuf:"bytes,12,rep,name=history_addresses,json=historyAddresses,proto3" json:"history_addresses,omitempty"`
	Sex              uint32                   `protobuf:"varint,13,opt,name=sex,proto3" json:"sex,omitempty"`
	Desc             *common.Desc             `protobuf:"bytes,14,opt,name=desc,proto3" json:"desc,omitempty"`
	Desc2            *common.Desc2            `protobuf:"bytes,15,opt,name=desc2,proto3" json:"desc2,omitempty"`
	Desc3            *common.Desc3            `protobuf:"bytes,16,opt,name=desc3,proto3" json:"desc3,omitempty"`
	RegisterAt       uint64                   `protobuf:"varint,17,opt,name=register_at,json=registerAt,proto3" json:"register_at,omitempty"`
	LoginAt          uint64                   `protobuf:"varint,18,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	Uuid             string                   `protobuf:"bytes,19,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Desc4            *User_Desc4              `protobuf:"bytes,20,opt,name=desc4,proto3" json:"desc4,omitempty"`
	Desc4M           map[string]*User_Desc4   `protobuf:"bytes,21,rep,name=desc4m,proto3" json:"desc4m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc4S           []*User_Desc4            `protobuf:"bytes,22,rep,name=desc4s,proto3" json:"desc4s,omitempty"`
	Descs            []*common.Desc           `protobuf:"bytes,23,rep,name=descs,proto3" json:"descs,omitempty"`
	Mm               map[string]string        `protobuf:"bytes,24,rep,name=mm,proto3" json:"mm,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Descm            map[string]*common.Desc  `protobuf:"bytes,25,rep,name=descm,proto3" json:"descm,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc2S           []*common.Desc2          `protobuf:"bytes,36,rep,name=desc2s,proto3" json:"desc2s,omitempty"`
	Desc3S           []*common.Desc3          `protobuf:"bytes,37,rep,name=desc3s,proto3" json:"desc3s,omitempty"`
	Desc2M           map[string]*common.Desc2 `protobuf:"bytes,38,rep,name=desc2m,proto3" json:"desc2m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc3M           map[string]*common.Desc3 `protobuf:"bytes,39,rep,name=desc3m,proto3" json:"desc3m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc5M           map[string]*User_Desc5   `protobuf:"bytes,40,rep,name=desc5m,proto3" json:"desc5m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc6S           []*User_Desc6            `protobuf:"bytes,41,rep,name=desc6s,proto3" json:"desc6s,omitempty"`
	Desc6M           map[string]*User_Desc6   `protobuf:"bytes,42,rep,name=desc6m,proto3" json:"desc6m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc7M           map[string]*User_Desc7   `protobuf:"bytes,43,rep,name=desc7m,proto3" json:"desc7m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc8M           map[string]*User_Desc8   `protobuf:"bytes,44,rep,name=desc8m,proto3" json:"desc8m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetHistoryAddresses() []*Address {
	if x != nil {
		return x.HistoryAddresses
	}
	return nil
}

func (x *User) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *User) GetDesc() *common.Desc {
	if x != nil {
		return x.Desc
	}
	return nil
}

func (x *User) GetDesc2() *common.Desc2 {
	if x != nil {
		return x.Desc2
	}
	return nil
}

func (x *User) GetDesc3() *common.Desc3 {
	if x != nil {
		return x.Desc3
	}
	return nil
}

func (x *User) GetRegisterAt() uint64 {
	if x != nil {
		return x.RegisterAt
	}
	return 0
}

func (x *User) GetLoginAt() uint64 {
	if x != nil {
		return x.LoginAt
	}
	return 0
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetDesc4() *User_Desc4 {
	if x != nil {
		return x.Desc4
	}
	return nil
}

func (x *User) GetDesc4M() map[string]*User_Desc4 {
	if x != nil {
		return x.Desc4M
	}
	return nil
}

func (x *User) GetDesc4S() []*User_Desc4 {
	if x != nil {
		return x.Desc4S
	}
	return nil
}

func (x *User) GetDescs() []*common.Desc {
	if x != nil {
		return x.Descs
	}
	return nil
}

func (x *User) GetMm() map[string]string {
	if x != nil {
		return x.Mm
	}
	return nil
}

func (x *User) GetDescm() map[string]*common.Desc {
	if x != nil {
		return x.Descm
	}
	return nil
}

func (x *User) GetDesc2S() []*common.Desc2 {
	if x != nil {
		return x.Desc2S
	}
	return nil
}

func (x *User) GetDesc3S() []*common.Desc3 {
	if x != nil {
		return x.Desc3S
	}
	return nil
}

func (x *User) GetDesc2M() map[string]*common.Desc2 {
	if x != nil {
		return x.Desc2M
	}
	return nil
}

func (x *User) GetDesc3M() map[string]*common.Desc3 {
	if x != nil {
		return x.Desc3M
	}
	return nil
}

func (x *User) GetDesc5M() map[string]*User_Desc5 {
	if x != nil {
		return x.Desc5M
	}
	return nil
}

func (x *User) GetDesc6S() []*User_Desc6 {
	if x != nil {
		return x.Desc6S
	}
	return nil
}

func (x *User) GetDesc6M() map[string]*User_Desc6 {
	if x != nil {
		return x.Desc6M
	}
	return nil
}

func (x *User) GetDesc7M() map[string]*User_Desc7 {
	if x != nil {
		return x.Desc7M
	}
	return nil
}

func (x *User) GetDesc8M() map[string]*User_Desc8 {
	if x != nil {
		return x.Desc8M
	}
	return nil
}

type User_Desc4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang5         string                 `protobuf:"bytes,1,opt,name=lang5,proto3" json:"lang5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Desc4) Reset() {
	*x = User_Desc4{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Desc4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Desc4) ProtoMessage() {}

func (x *User_Desc4) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Desc4.ProtoReflect.Descriptor instead.
func (*User_Desc4) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 0}
}

func (x *User_Desc4) GetLang5() string {
	if x != nil {
		return x.Lang5
	}
	return ""
}

type User_Desc5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desc          string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Desc5) Reset() {
	*x = User_Desc5{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Desc5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Desc5) ProtoMessage() {}

func (x *User_Desc5) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Desc5.ProtoReflect.Descriptor instead.
func (*User_Desc5) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 1}
}

func (x *User_Desc5) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type User_Desc6 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Desc6) Reset() {
	*x = User_Desc6{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Desc6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Desc6) ProtoMessage() {}

func (x *User_Desc6) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Desc6.ProtoReflect.Descriptor instead.
func (*User_Desc6) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 2}
}

type User_Desc7 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Desc7) Reset() {
	*x = User_Desc7{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Desc7) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Desc7) ProtoMessage() {}

func (x *User_Desc7) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Desc7.ProtoReflect.Descriptor instead.
func (*User_Desc7) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 3}
}

type User_Desc8 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Desc8) Reset() {
	*x = User_Desc8{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Desc8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Desc8) ProtoMessage() {}

func (x *User_Desc8) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Desc8.ProtoReflect.Descriptor instead.
func (*User_Desc8) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 4}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x0fmgorm/ext.proto\x1a\n" +
	"comm.proto\"\x93\x01\n" +
	"\aAddress\x12+\n" +
	"\x06street\x18\x01 \x01(\tB\x13\x8a\x8e%\x0f\n" +
	"\astreets\x12\x04roadR\x06street\x128\n" +
	"\x04city\x18\x02 \x01(\tB$\x8a\x8e% \n" +
	"\x10cities,omitempty\x12\fct,omitemptyR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry:\a\x8a\x8e%\x03\x80\x01\x01\"\xf4\x11\n" +
	"\x04User\x129\n" +
	"\x02id\x18\x01 \x01(\x04B)\x8a\x8e%%\n" +
	"\x02id\x12\x02id\"\x1bschema:\"title=唯一标识\"R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x02R\abalance\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12\x16\n" +
	"\x06avatar\x18\b \x01(\fR\x06avatar\x12(\n" +
	"\x04tags\x18\t \x03(\v2\x14.user.User.TagsEntryR\x04tags\x12\x1c\n" +
	"\tinterests\x18\n" +
	" \x03(\tR\tinterests\x12'\n" +
	"\aaddress\x18\v \x01(\v2\r.user.AddressR\aaddress\x12:\n" +
	"\x11history_addresses\x18\f \x03(\v2\r.user.AddressR\x10historyAddresses\x12\x10\n" +
	"\x03sex\x18\r \x01(\rR\x03sex\x12 \n" +
	"\x04desc\x18\x0e \x01(\v2\f.common.DescR\x04desc\x12#\n" +
	"\x05desc2\x18\x0f \x01(\v2\r.common.Desc2R\x05desc2\x12#\n" +
	"\x05desc3\x18\x10 \x01(\v2\r.common.Desc3R\x05desc3\x12'\n" +
	"\vregister_at\x18\x11 \x01(\x04B\x06\x8a\x8e%\x02\x18\x01R\n" +
	"registerAt\x12!\n" +
	"\blogin_at\x18\x12 \x01(\x04B\x06\x8a\x8e%\x02\x18\x01R\aloginAt\x12\x1a\n" +
	"\x04uuid\x18\x13 \x01(\tB\x06\x8a\x8e%\x02\x18\x02R\x04uuid\x12&\n" +
	"\x05desc4\x18\x14 \x01(\v2\x10.user.User.Desc4R\x05desc4\x12.\n" +
	"\x06desc4m\x18\x15 \x03(\v2\x16.user.User.Desc4mEntryR\x06desc4m\x12(\n" +
	"\x06desc4s\x18\x16 \x03(\v2\x10.user.User.Desc4R\x06desc4s\x12\"\n" +
	"\x05descs\x18\x17 \x03(\v2\f.common.DescR\x05descs\x12\"\n" +
	"\x02mm\x18\x18 \x03(\v2\x12.user.User.MmEntryR\x02mm\x12+\n" +
	"\x05descm\x18\x19 \x03(\v2\x15.user.User.DescmEntryR\x05descm\x12%\n" +
	"\x06desc2s\x18$ \x03(\v2\r.common.Desc2R\x06desc2s\x12%\n" +
	"\x06desc3s\x18% \x03(\v2\r.common.Desc3R\x06desc3s\x12.\n" +
	"\x06desc2m\x18& \x03(\v2\x16.user.User.Desc2mEntryR\x06desc2m\x12.\n" +
	"\x06desc3m\x18' \x03(\v2\x16.user.User.Desc3mEntryR\x06desc3m\x12.\n" +
	"\x06desc5m\x18( \x03(\v2\x16.user.User.Desc5mEntryR\x06desc5m\x12(\n" +
	"\x06desc6s\x18) \x03(\v2\x10.user.User.Desc6R\x06desc6s\x12.\n" +
	"\x06desc6m\x18* \x03(\v2\x16.user.User.Desc6mEntryR\x06desc6m\x12.\n" +
	"\x06desc7m\x18+ \x03(\v2\x16.user.User.Desc7mEntryR\x06desc7m\x12.\n" +
	"\x06desc8m\x18, \x03(\v2\x16.user.User.Desc8mEntryR\x06desc8m\x1a-\n" +
	"\x05Desc4\x12$\n" +
	"\x05lang5\x18\x01 \x01(\tB\x0e\x8a\x8e%\n" +
	"\n" +
	"\blanguageR\x05lang5\x1a\x1b\n" +
	"\x05Desc5\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x1a\a\n" +
	"\x05Desc6\x1a\x10\n" +
	"\x05Desc7:\a\x8a\x8e%\x03\x80\x01\x01\x1a)\n" +
	"\x05Desc8: \x8a\x8e%\x1c\x12\fincorrect_db\x1a\fincorrect_tb\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aK\n" +
	"\vDesc4mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.user.User.Desc4R\x05value:\x028\x01\x1a5\n" +
	"\aMmEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aF\n" +
	"\n" +
	"DescmEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.common.DescR\x05value:\x028\x01\x1aH\n" +
	"\vDesc2mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.common.Desc2R\x05value:\x028\x01\x1aH\n" +
	"\vDesc3mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.common.Desc3R\x05value:\x028\x01\x1aK\n" +
	"\vDesc5mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.user.User.Desc5R\x05value:\x028\x01\x1aK\n" +
	"\vDesc6mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.user.User.Desc6R\x05value:\x028\x01\x1aK\n" +
	"\vDesc7mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.user.User.Desc7R\x05value:\x028\x01\x1aK\n" +
	"\vDesc8mEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.user.User.Desc8R\x05value:\x028\x01:\x8b\x01\x8a\x8e%\x86\x01\x12\x0ftest_example_%s\x1a\ruser_%d_%d_%s \x01*\n" +
	"sex:gender*\fusername,age*\vregister_at*\x04uuid:\x02id:\x0eemail,username:\x1fusername,address.city:user_cityh\aB/Z-github.com/995933447/mgorm/mgorm-example/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_user_proto_goTypes = []any{
	(*Address)(nil),      // 0: user.Address
	(*User)(nil),         // 1: user.User
	(*User_Desc4)(nil),   // 2: user.User.Desc4
	(*User_Desc5)(nil),   // 3: user.User.Desc5
	(*User_Desc6)(nil),   // 4: user.User.Desc6
	(*User_Desc7)(nil),   // 5: user.User.Desc7
	(*User_Desc8)(nil),   // 6: user.User.Desc8
	nil,                  // 7: user.User.TagsEntry
	nil,                  // 8: user.User.Desc4mEntry
	nil,                  // 9: user.User.MmEntry
	nil,                  // 10: user.User.DescmEntry
	nil,                  // 11: user.User.Desc2mEntry
	nil,                  // 12: user.User.Desc3mEntry
	nil,                  // 13: user.User.Desc5mEntry
	nil,                  // 14: user.User.Desc6mEntry
	nil,                  // 15: user.User.Desc7mEntry
	nil,                  // 16: user.User.Desc8mEntry
	(*common.Desc)(nil),  // 17: common.Desc
	(*common.Desc2)(nil), // 18: common.Desc2
	(*common.Desc3)(nil), // 19: common.Desc3
}
var file_user_proto_depIdxs = []int32{
	7,  // 0: user.User.tags:type_name -> user.User.TagsEntry
	0,  // 1: user.User.address:type_name -> user.Address
	0,  // 2: user.User.history_addresses:type_name -> user.Address
	17, // 3: user.User.desc:type_name -> common.Desc
	18, // 4: user.User.desc2:type_name -> common.Desc2
	19, // 5: user.User.desc3:type_name -> common.Desc3
	2,  // 6: user.User.desc4:type_name -> user.User.Desc4
	8,  // 7: user.User.desc4m:type_name -> user.User.Desc4mEntry
	2,  // 8: user.User.desc4s:type_name -> user.User.Desc4
	17, // 9: user.User.descs:type_name -> common.Desc
	9,  // 10: user.User.mm:type_name -> user.User.MmEntry
	10, // 11: user.User.descm:type_name -> user.User.DescmEntry
	18, // 12: user.User.desc2s:type_name -> common.Desc2
	19, // 13: user.User.desc3s:type_name -> common.Desc3
	11, // 14: user.User.desc2m:type_name -> user.User.Desc2mEntry
	12, // 15: user.User.desc3m:type_name -> user.User.Desc3mEntry
	13, // 16: user.User.desc5m:type_name -> user.User.Desc5mEntry
	4,  // 17: user.User.desc6s:type_name -> user.User.Desc6
	14, // 18: user.User.desc6m:type_name -> user.User.Desc6mEntry
	15, // 19: user.User.desc7m:type_name -> user.User.Desc7mEntry
	16, // 20: user.User.desc8m:type_name -> user.User.Desc8mEntry
	2,  // 21: user.User.Desc4mEntry.value:type_name -> user.User.Desc4
	17, // 22: user.User.DescmEntry.value:type_name -> common.Desc
	18, // 23: user.User.Desc2mEntry.value:type_name -> common.Desc2
	19, // 24: user.User.Desc3mEntry.value:type_name -> common.Desc3
	3,  // 25: user.User.Desc5mEntry.value:type_name -> user.User.Desc5
	4,  // 26: user.User.Desc6mEntry.value:type_name -> user.User.Desc6
	5,  // 27: user.User.Desc7mEntry.value:type_name -> user.User.Desc7
	6,  // 28: user.User.Desc8mEntry.value:type_name -> user.User.Desc8
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
