// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: comm.proto

package common

import (
	base "github.com/995933447/mgorm/mgorm-example/base"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Desc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Desc) Reset() {
	*x = Desc{}
	mi := &file_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Desc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Desc) ProtoMessage() {}

func (x *Desc) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Desc.ProtoReflect.Descriptor instead.
func (*Desc) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{0}
}

func (x *Desc) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type Desc2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Desc2) Reset() {
	*x = Desc2{}
	mi := &file_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Desc2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Desc2) ProtoMessage() {}

func (x *Desc2) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Desc2.ProtoReflect.Descriptor instead.
func (*Desc2) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{1}
}

func (x *Desc2) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type Desc3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Corp          *base.Corp             `protobuf:"bytes,2,opt,name=corp,proto3" json:"corp,omitempty"`
	App           *base.App              `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Desc3) Reset() {
	*x = Desc3{}
	mi := &file_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Desc3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Desc3) ProtoMessage() {}

func (x *Desc3) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Desc3.ProtoReflect.Descriptor instead.
func (*Desc3) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{2}
}

func (x *Desc3) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Desc3) GetCorp() *base.Corp {
	if x != nil {
		return x.Corp
	}
	return nil
}

func (x *Desc3) GetApp() *base.App {
	if x != nil {
		return x.App
	}
	return nil
}

var File_comm_proto protoreflect.FileDescriptor

const file_comm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"comm.proto\x12\x06common\x1a\x0fmgorm/ext.proto\x1a\n" +
	"base.proto\"\x1a\n" +
	"\x04Desc\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\">\n" +
	"\x05Desc2\x12,\n" +
	"\x04lang\x18\x01 \x01(\tB\x18\x8a\x8e%\x14\n" +
	"\blanguage\x12\blanguageR\x04lang:\a\x8a\x8e%\x03\x80\x01\x01\"\x80\x01\n" +
	"\x05Desc3\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x1e\n" +
	"\x04corp\x18\x02 \x01(\v2\n" +
	".base.CorpR\x04corp\x12\x1b\n" +
	"\x03app\x18\x03 \x01(\v2\t.base.AppR\x03app:&\x8a\x8e%\"\n" +
	"\n" +
	"default_%d\x12\rexample_db_%d\x1a\x05desc3B1Z/github.com/995933447/mgorm/mgorm-example/commonb\x06proto3"

var (
	file_comm_proto_rawDescOnce sync.Once
	file_comm_proto_rawDescData []byte
)

func file_comm_proto_rawDescGZIP() []byte {
	file_comm_proto_rawDescOnce.Do(func() {
		file_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comm_proto_rawDesc), len(file_comm_proto_rawDesc)))
	})
	return file_comm_proto_rawDescData
}

var file_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_comm_proto_goTypes = []any{
	(*Desc)(nil),      // 0: common.Desc
	(*Desc2)(nil),     // 1: common.Desc2
	(*Desc3)(nil),     // 2: common.Desc3
	(*base.Corp)(nil), // 3: base.Corp
	(*base.App)(nil),  // 4: base.App
}
var file_comm_proto_depIdxs = []int32{
	3, // 0: common.Desc3.corp:type_name -> base.Corp
	4, // 1: common.Desc3.app:type_name -> base.App
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comm_proto_init() }
func file_comm_proto_init() {
	if File_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comm_proto_rawDesc), len(file_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_proto_goTypes,
		DependencyIndexes: file_comm_proto_depIdxs,
		MessageInfos:      file_comm_proto_msgTypes,
	}.Build()
	File_comm_proto = out.File
	file_comm_proto_goTypes = nil
	file_comm_proto_depIdxs = nil
}
