// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: mgorm_ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FieldTypeNil      FieldType = 0
	FieldType_FieldTypeDatetime FieldType = 1 // 时间类型
	FieldType_FieldTypeObjectId FieldType = 2 // object id类型
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FieldTypeNil",
		1: "FieldTypeDatetime",
		2: "FieldTypeObjectId",
	}
	FieldType_value = map[string]int32{
		"FieldTypeNil":      0,
		"FieldTypeDatetime": 1,
		"FieldTypeObjectId": 2,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_mgorm_ext_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_mgorm_ext_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_mgorm_ext_proto_rawDescGZIP(), []int{0}
}

type MgormOptions struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Conn                    string                 `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`                                                                            // 连接名称,支持自动水平扩展切分,如default_conn_%s_%d、scrm_%d
	Db                      string                 `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`                                                                                // 数据库名称,支持自动水平扩展切分,如biz_%s_%d、biz2_%d
	Tb                      string                 `protobuf:"bytes,3,opt,name=tb,proto3" json:"tb,omitempty"`                                                                                // 集合名称,支持自动水平扩展切分,如user_%s_%d、wallet_%d
	Cached                  bool                   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`                                                                       // 是否启用缓存
	IndexKeys               []string               `protobuf:"bytes,5,rep,name=index_keys,json=indexKeys,proto3" json:"index_keys,omitempty"`                                                 // 普通索引
	ExpireIndexKeys         []string               `protobuf:"bytes,6,rep,name=expire_index_keys,json=expireIndexKeys,proto3" json:"expire_index_keys,omitempty"`                             // 过期索引
	UniqIndexKeys           []string               `protobuf:"bytes,7,rep,name=uniq_index_keys,json=uniqIndexKeys,proto3" json:"uniq_index_keys,omitempty"`                                   // 唯一索引
	DisabledAutoCreatedAt   bool                   `protobuf:"varint,8,opt,name=disabled_auto_created_at,json=disabledAutoCreatedAt,proto3" json:"disabled_auto_created_at,omitempty"`        // 是否禁用自动创建created_at字段
	DisabledAutoUpdatedAt   bool                   `protobuf:"varint,9,opt,name=disabled_auto_updated_at,json=disabledAutoUpdatedAt,proto3" json:"disabled_auto_updated_at,omitempty"`        // 是否禁用自动创建updated_at字段
	DisabledAutoExpireAt    bool                   `protobuf:"varint,10,opt,name=disabled_auto_expire_at,json=disabledAutoExpireAt,proto3" json:"disabled_auto_expire_at,omitempty"`          // 是否禁用自动创建expire_at字段,启用后没有指定过期索引的情况下将把expire_at作为默认的过期索引
	PrimaryIdFieldName      string                 `protobuf:"bytes,12,opt,name=primary_id_field_name,json=primaryIdFieldName,proto3" json:"primary_id_field_name,omitempty"`                 // 指定主键_id字段名称,不设置则默认采用ID
	ExpireTtlDays           int64                  `protobuf:"varint,13,opt,name=expire_ttl_days,json=expireTtlDays,proto3" json:"expire_ttl_days,omitempty"`                                 // 过期索引过期时间，仅作用于expire_at字段
	OrmStructNameSuffix     string                 `protobuf:"bytes,14,opt,name=orm_struct_name_suffix,json=ormStructNameSuffix,proto3" json:"orm_struct_name_suffix,omitempty"`              // 指定生成的结构体名称尾缀，不设置则默认采用Orm
	OrmModelNameSuffix      string                 `protobuf:"bytes,15,opt,name=orm_model_name_suffix,json=ormModelNameSuffix,proto3" json:"orm_model_name_suffix,omitempty"`                 // 指定生成的Model名称尾缀,不设置则默认Model
	IsPureStruct            bool                   `protobuf:"varint,16,opt,name=is_pure_struct,json=isPureStruct,proto3" json:"is_pure_struct,omitempty"`                                    // 是否只生成结构体,不生成Model,常用与集合里面内嵌的集合结构体
	OmitemptyDefaultBsonTag bool                   `protobuf:"varint,17,opt,name=omitempty_default_bson_tag,json=omitemptyDefaultBsonTag,proto3" json:"omitempty_default_bson_tag,omitempty"` // 生成bson tag时候是否默认omitempty
	OmitemptyDefaultJsonTag bool                   `protobuf:"varint,18,opt,name=omitempty_default_json_tag,json=omitemptyDefaultJsonTag,proto3" json:"omitempty_default_json_tag,omitempty"` // 生成json tag时候是否默认omitempty
	Desc                    string                 `protobuf:"bytes,19,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MgormOptions) Reset() {
	*x = MgormOptions{}
	mi := &file_mgorm_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MgormOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MgormOptions) ProtoMessage() {}

func (x *MgormOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mgorm_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MgormOptions.ProtoReflect.Descriptor instead.
func (*MgormOptions) Descriptor() ([]byte, []int) {
	return file_mgorm_ext_proto_rawDescGZIP(), []int{0}
}

func (x *MgormOptions) GetConn() string {
	if x != nil {
		return x.Conn
	}
	return ""
}

func (x *MgormOptions) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *MgormOptions) GetTb() string {
	if x != nil {
		return x.Tb
	}
	return ""
}

func (x *MgormOptions) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *MgormOptions) GetIndexKeys() []string {
	if x != nil {
		return x.IndexKeys
	}
	return nil
}

func (x *MgormOptions) GetExpireIndexKeys() []string {
	if x != nil {
		return x.ExpireIndexKeys
	}
	return nil
}

func (x *MgormOptions) GetUniqIndexKeys() []string {
	if x != nil {
		return x.UniqIndexKeys
	}
	return nil
}

func (x *MgormOptions) GetDisabledAutoCreatedAt() bool {
	if x != nil {
		return x.DisabledAutoCreatedAt
	}
	return false
}

func (x *MgormOptions) GetDisabledAutoUpdatedAt() bool {
	if x != nil {
		return x.DisabledAutoUpdatedAt
	}
	return false
}

func (x *MgormOptions) GetDisabledAutoExpireAt() bool {
	if x != nil {
		return x.DisabledAutoExpireAt
	}
	return false
}

func (x *MgormOptions) GetPrimaryIdFieldName() string {
	if x != nil {
		return x.PrimaryIdFieldName
	}
	return ""
}

func (x *MgormOptions) GetExpireTtlDays() int64 {
	if x != nil {
		return x.ExpireTtlDays
	}
	return 0
}

func (x *MgormOptions) GetOrmStructNameSuffix() string {
	if x != nil {
		return x.OrmStructNameSuffix
	}
	return ""
}

func (x *MgormOptions) GetOrmModelNameSuffix() string {
	if x != nil {
		return x.OrmModelNameSuffix
	}
	return ""
}

func (x *MgormOptions) GetIsPureStruct() bool {
	if x != nil {
		return x.IsPureStruct
	}
	return false
}

func (x *MgormOptions) GetOmitemptyDefaultBsonTag() bool {
	if x != nil {
		return x.OmitemptyDefaultBsonTag
	}
	return false
}

func (x *MgormOptions) GetOmitemptyDefaultJsonTag() bool {
	if x != nil {
		return x.OmitemptyDefaultJsonTag
	}
	return false
}

func (x *MgormOptions) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type MgormFieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BsonTag       string                 `protobuf:"bytes,1,opt,name=bson_tag,json=bsonTag,proto3" json:"bson_tag,omitempty"`                                 // 自定义字段的tag bson
	JsonTag       string                 `protobuf:"bytes,2,opt,name=json_tag,json=jsonTag,proto3" json:"json_tag,omitempty"`                                 // 自定义字段的tag json
	FieldType     FieldType              `protobuf:"varint,3,opt,name=field_type,json=fieldType,proto3,enum=mgorm_ext.FieldType" json:"field_type,omitempty"` // 自定义字段的特殊类型
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`                                                      // 自定义tags,如果设置该选项,则会直接采用tags作为最终tags,即时定义了bson_tag或json_tag,也会被tags覆盖
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MgormFieldOptions) Reset() {
	*x = MgormFieldOptions{}
	mi := &file_mgorm_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MgormFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MgormFieldOptions) ProtoMessage() {}

func (x *MgormFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mgorm_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MgormFieldOptions.ProtoReflect.Descriptor instead.
func (*MgormFieldOptions) Descriptor() ([]byte, []int) {
	return file_mgorm_ext_proto_rawDescGZIP(), []int{1}
}

func (x *MgormFieldOptions) GetBsonTag() string {
	if x != nil {
		return x.BsonTag
	}
	return ""
}

func (x *MgormFieldOptions) GetJsonTag() string {
	if x != nil {
		return x.JsonTag
	}
	return ""
}

func (x *MgormFieldOptions) GetFieldType() FieldType {
	if x != nil {
		return x.FieldType
	}
	return FieldType_FieldTypeNil
}

func (x *MgormFieldOptions) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

var file_mgorm_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MgormOptions)(nil),
		Field:         76001,
		Name:          "mgorm_ext.mgorm_opts",
		Tag:           "bytes,76001,opt,name=mgorm_opts",
		Filename:      "mgorm_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*MgormFieldOptions)(nil),
		Field:         76001,
		Name:          "mgorm_ext.mgorm_field_opts",
		Tag:           "bytes,76001,opt,name=mgorm_field_opts",
		Filename:      "mgorm_ext.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional mgorm_ext.MgormOptions mgorm_opts = 76001;
	E_MgormOpts = &file_mgorm_ext_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional mgorm_ext.MgormFieldOptions mgorm_field_opts = 76001;
	E_MgormFieldOpts = &file_mgorm_ext_proto_extTypes[1]
)

var File_mgorm_ext_proto protoreflect.FileDescriptor

const file_mgorm_ext_proto_rawDesc = "" +
	"\n" +
	"\x0fmgorm_ext.proto\x12\tmgorm_ext\x1a google/protobuf/descriptor.proto\"\xed\x05\n" +
	"\fMgormOptions\x12\x12\n" +
	"\x04conn\x18\x01 \x01(\tR\x04conn\x12\x0e\n" +
	"\x02db\x18\x02 \x01(\tR\x02db\x12\x0e\n" +
	"\x02tb\x18\x03 \x01(\tR\x02tb\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\x12\x1d\n" +
	"\n" +
	"index_keys\x18\x05 \x03(\tR\tindexKeys\x12*\n" +
	"\x11expire_index_keys\x18\x06 \x03(\tR\x0fexpireIndexKeys\x12&\n" +
	"\x0funiq_index_keys\x18\a \x03(\tR\runiqIndexKeys\x127\n" +
	"\x18disabled_auto_created_at\x18\b \x01(\bR\x15disabledAutoCreatedAt\x127\n" +
	"\x18disabled_auto_updated_at\x18\t \x01(\bR\x15disabledAutoUpdatedAt\x125\n" +
	"\x17disabled_auto_expire_at\x18\n" +
	" \x01(\bR\x14disabledAutoExpireAt\x121\n" +
	"\x15primary_id_field_name\x18\f \x01(\tR\x12primaryIdFieldName\x12&\n" +
	"\x0fexpire_ttl_days\x18\r \x01(\x03R\rexpireTtlDays\x123\n" +
	"\x16orm_struct_name_suffix\x18\x0e \x01(\tR\x13ormStructNameSuffix\x121\n" +
	"\x15orm_model_name_suffix\x18\x0f \x01(\tR\x12ormModelNameSuffix\x12$\n" +
	"\x0eis_pure_struct\x18\x10 \x01(\bR\fisPureStruct\x12;\n" +
	"\x1aomitempty_default_bson_tag\x18\x11 \x01(\bR\x17omitemptyDefaultBsonTag\x12;\n" +
	"\x1aomitempty_default_json_tag\x18\x12 \x01(\bR\x17omitemptyDefaultJsonTag\x12\x12\n" +
	"\x04desc\x18\x13 \x01(\tR\x04desc\"\x92\x01\n" +
	"\x11MgormFieldOptions\x12\x19\n" +
	"\bbson_tag\x18\x01 \x01(\tR\absonTag\x12\x19\n" +
	"\bjson_tag\x18\x02 \x01(\tR\ajsonTag\x123\n" +
	"\n" +
	"field_type\x18\x03 \x01(\x0e2\x14.mgorm_ext.FieldTypeR\tfieldType\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags*K\n" +
	"\tFieldType\x12\x10\n" +
	"\fFieldTypeNil\x10\x00\x12\x15\n" +
	"\x11FieldTypeDatetime\x10\x01\x12\x15\n" +
	"\x11FieldTypeObjectId\x10\x02:Y\n" +
	"\n" +
	"mgorm_opts\x12\x1f.google.protobuf.MessageOptions\x18\xe1\xd1\x04 \x01(\v2\x17.mgorm_ext.MgormOptionsR\tmgormOpts:g\n" +
	"\x10mgorm_field_opts\x12\x1d.google.protobuf.FieldOptions\x18\xe1\xd1\x04 \x01(\v2\x1c.mgorm_ext.MgormFieldOptionsR\x0emgormFieldOptsB\x1fZ\x1dgithub.com/995933447/mgorm/pbb\x06proto3"

var (
	file_mgorm_ext_proto_rawDescOnce sync.Once
	file_mgorm_ext_proto_rawDescData []byte
)

func file_mgorm_ext_proto_rawDescGZIP() []byte {
	file_mgorm_ext_proto_rawDescOnce.Do(func() {
		file_mgorm_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mgorm_ext_proto_rawDesc), len(file_mgorm_ext_proto_rawDesc)))
	})
	return file_mgorm_ext_proto_rawDescData
}

var file_mgorm_ext_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mgorm_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mgorm_ext_proto_goTypes = []any{
	(FieldType)(0),                      // 0: mgorm_ext.FieldType
	(*MgormOptions)(nil),                // 1: mgorm_ext.MgormOptions
	(*MgormFieldOptions)(nil),           // 2: mgorm_ext.MgormFieldOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_mgorm_ext_proto_depIdxs = []int32{
	0, // 0: mgorm_ext.MgormFieldOptions.field_type:type_name -> mgorm_ext.FieldType
	3, // 1: mgorm_ext.mgorm_opts:extendee -> google.protobuf.MessageOptions
	4, // 2: mgorm_ext.mgorm_field_opts:extendee -> google.protobuf.FieldOptions
	1, // 3: mgorm_ext.mgorm_opts:type_name -> mgorm_ext.MgormOptions
	2, // 4: mgorm_ext.mgorm_field_opts:type_name -> mgorm_ext.MgormFieldOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mgorm_ext_proto_init() }
func file_mgorm_ext_proto_init() {
	if File_mgorm_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mgorm_ext_proto_rawDesc), len(file_mgorm_ext_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_mgorm_ext_proto_goTypes,
		DependencyIndexes: file_mgorm_ext_proto_depIdxs,
		EnumInfos:         file_mgorm_ext_proto_enumTypes,
		MessageInfos:      file_mgorm_ext_proto_msgTypes,
		ExtensionInfos:    file_mgorm_ext_proto_extTypes,
	}.Build()
	File_mgorm_ext_proto = out.File
	file_mgorm_ext_proto_goTypes = nil
	file_mgorm_ext_proto_depIdxs = nil
}
